project:
  type: website
  output-dir: docs

execute:
  freeze: auto  

format:
  html:
    theme: cosmo

website:
  page-navigation: true
  back-to-top-navigation: true

  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/Kubus42/llm_seminar
          - text: Report a Bug
            url:  https://github.com/Kubus42/llm_seminar/issues
    title: "Seminar: Large Language Models"
    left:
      - text: "Seminar"
        file: "index.qmd"
      - text: "Resources"
        file: resources/packages.qmd
    
  sidebar:

    - title: "Seminar"
      search: false
      
      contents:
        - section: "About"
          contents:
            - index.qmd
            - about/projects.qmd

        - section: "Python Crash Course"
          contents: 
            - python_intro/overview.qmd
            - python_intro/data_types.qmd
            - python_intro/exercises/data_types.ipynb
            - python_intro/string_operations.qmd
            - python_intro/exercises/strings.ipynb
            - python_intro/lists_and_loops.qmd
            - python_intro/exercises/lists_and_loops.ipynb
            - python_intro/functions.qmd
            - python_intro/exercises/functions.ipynb
            - python_intro/conditional_statements.qmd
            - python_intro/exercises/conditional_statements.ipynb
            - python_intro/dictionaries.qmd
            - python_intro/exercises/dictionaries.ipynb
            - python_intro/classes.qmd
            - python_intro/exercises/classes.ipynb

        - section: "Natural Language Processing"
          contents:
            - nlp/overview.qmd
            - nlp/tokenization.qmd
            - nlp/exercises/ex_tokenization.ipynb
            - nlp/exercises/ex_word_matching.ipynb
            - nlp/fuzzy_matching.qmd
            - nlp/exercises/ex_fuzzy_matching.ipynb 
            - nlp/statistical_text_analysis.qmd
            - nlp/exercises/ex_tfidf.ipynb

        - section: "Large Language Models"
          contents:
            - llm/intro.qmd
            - llm/gpt.qmd
            - llm/gpt_api.qmd
            - llm/exercises/ex_gpt_start.ipynb
            - llm/exercises/ex_gpt_chatbot.ipynb
            - llm/prompting.qmd
            - llm/parameterization.qmd
            - llm/exercises/ex_gpt_parameterization.ipynb
            - llm/exercises/ex_gpt_ner_with_function_calls.ipynb

        - section: "Embeddings"
          contents: 
            - embeddings/embeddings.qmd
            - embeddings/exercises/ex_emb_similarity.ipynb
            - embeddings/visualization.qmd

        - section: "Ethical Considerations"
          contents: 
            - ethics/bias.qmd
            - ethics/data_privacy.qmd
          
      style: "docked"
      collapse-level: 1
      
    - title: "Resources"
      contents:
        - text: "Python packages"
          url: resources/packages.qmd
        - text: "List of exercises"
          url: resources/exercises.qmd
        - text: "Language model APIs"
          url: resources/apis.qmd
        - text: "Slides"
          url: resources/slides.qmd
            
  page-footer: 
    right: "Copyright 2024, Julian Rasch" 
