project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo

website:
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
    title: "LLM Seminar"
    left:
      - text: "Seminar"
        file: "index.qmd"
      - text: "Resources"
        file: "resources.qmd"
    
  sidebar:

    - title: "Seminar"
      search: false
      
      contents:
        - section: "About"
          contents:
            - index.qmd
            - about/schedule.qmd
            - about/projects.qmd
            - about/assignment.qmd

        - section: "Natural Language Processing"
          contents:
            - nlp/intro.qmd
            - nlp/history.qmd
            - nlp/tokenization.qmd
            - nlp/exercises/ex_tokenization.ipynb
            - nlp/fuzzy_matching.qmd

        - section: "Large Language Models"

        - section: "Embeddings"
          contents: 
            - embeddings/embeddings.qmd
            - embeddings/exercises/ex_emb_similarity.ipynb
            - embeddings/visualization.qmd
            - embeddings/clustering.qmd

        - section: "Parameterization"

        - section: "Ethical Considerations"

        - section: "Data Privacy"

        - section: "Exercises"
          contents: 
            - embeddings/exercises/ex_emb_similarity.ipynb
          
      style: "docked"
      collapse-level: 1
      
    - title: "Resources"
      contents:
        - text: "Resource 1"
          url: "resources.qmd"
        - text: "Resource 2"
          url: "test.qmd"
      
  page-footer: 
    right: "Copyright 2024, Julian Rasch" 
