---
title: "Projects"
format:
  html:
    code-fold: true
jupyter: python3
---

In the final part of the seminar we are going to tackle our very own projects involving a language model. 
At best, you find your ideas and work on them, maybe you even have a work-related application mind. 
The following list can serve as inspiration. 


### Project ideas

1. **Question-Answering Chatbot**: Build a chatbot that can answer questions posed by users on a specific topic provided in form of documents. Users input their questions, the chatbot retrieves relevant information from a pre-defined set of documents, and uses the information to answer the question.
2. **Document tagging / classification:** Use GPT and its tools (e.g., function calls) and/or embeddings to classify documents or assign tags to them. Example: Sort bug reports or complaints into categories depending on the problem.
3. **Clustering of text-based entities:** Create a small tool that can cluster text-based entities based on embeddings, for example, groups of texts or keywords. Example: Structure a folder of text files based on their content.
4. **Text-based RPG Game**: Develop a text-based role-playing game where players interact with characters and navigate through a story generated by GPT. Players make choices that influence the direction of the narrative.
5. **Sentiment Analysis Tool**: Build an app that analyzes the sentiment of text inputs (e.g., social media posts, customer reviews) using GPT. Users can input text, and the app provides insights into the overall sentiment expressed in the text.
6. **Text Summarization Tool**: Create an application that summarizes long blocks of text into shorter, concise summaries. Users can input articles, essays, or documents, and the tool generates a summarized version.
7. **Language Translation Tool**: Build a simple translation app that utilizes GPT to translate text between different languages. Users can input text in one language, and the app outputs the translated text in the desired language. Has to include some nice tweaks.
8.  **Personalized Recipe Generator**: Develop an app that generates personalized recipes based on user preferences and dietary restrictions. Users input their preferred ingredients and dietary needs, and the app generates custom recipes using GPT.
9.  **Lyrics Generator**: Create a lyrics generation tool that generates lyrics based on user input such as themes, music style, emotions, or keywords. Users can explore different poetic styles and themes generated by GPT.


### Project setup
TODO: Describe the idea of Dash and the app in Jupyterlab.
